version: '3.4'
services:
    nginx:
        image: nginx:1.13.6-alpine
        hostname: nginx
        ports:
            - 10000:80/tcp
        networks:
            wordpress:
                aliases:
                    - nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./www:/var/www/html:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 3
            resources:
                limits:
                    cpus: '0.50'
                    memory: 100M
            update_config:
                parallelism: 1
                delay: 10s
        healthcheck:
            test: ["CMD-SHELL", "nc -w 1 127.0.0.1 -z 80 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    wordpress:
        image: wordpress:4.9.5-php7.1-fpm
        hostname: php
        networks:
            wordpress:
                aliases:
                    - wordpress
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_TABLE_PREFIX=wp_
        volumes:
            - ./www:/var/www/html:rw
            - ./php/ext/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 3
            resources:
                limits:
                    cpus: '2'
                    memory: '1024G'
            update_config:
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    mysql:
        image: mysql:5.7.20
        hostname: mysql
        networks:
            wordpress:
                aliases:
                    - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '4'
                    memory: 1G
            update_config:
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        hostname: phpmyadmin
        ports:
            - 10001:80/tcp
        networks:
            wordpress:
                aliases:
                    - phpmyadmin
        environment:
            - PMA_HOST=mysql        
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                order: start-first
                parallelism: 1
                delay: 10s
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
            placement:
                constraints:
                    - node.labels.wp == true
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    redis-haproxy:
        image: haproxy:1.8.3-alpine
        hostname: redis-haproxy
        networks:
            wordpress:
                aliases:
                    - redis-haproxy
        volumes:
            - ./redis/redis-haproxy:/usr/local/etc/haproxy:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 2
            resources:
                limits:
                    cpus: '1'
                    memory: 200M
            update_config:
                parallelism: 1
                delay: 10s
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    redis-master:
        image: redis:4.0.6
        hostname: redis-master
        networks:
            wordpress:
                aliases:
                    - redis-master
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 200M
            update_config:
                parallelism: 1
                delay: 10s
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 PING &> /dev/null || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    redis-slave:
        image: redis:4.0.6
        hostname: redis-slave
        command: redis-server --slaveof redis-master 6379
        networks:
            wordpress:
                aliases:
                    - redis-slave
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 200M
            update_config:
                parallelism: 1
                delay: 10s
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 PING &> /dev/null || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    redis-sentinel:
        image: redis:4.0.6
        hostname: redis-sentinel
        command: redis-sentinel /etc/redis/sentinel.conf --sentinel
        networks:
            wordpress:
                aliases:
                    - redis-sentinel
        volumes:
            - ./redis/redis-sentinel/sentinel.conf:/etc/redis/sentinel.conf:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 200M
            update_config:
                parallelism: 1
                delay: 10s
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 PING &> /dev/null || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

networks:
    wordpress:
        external: true
